"""initial schema

Revision ID: fdd3e7f932d6
Revises: 
Create Date: 2026-09-11 00:22:17.768886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdd3e7f932d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complaint_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_number', sa.String(length=30), nullable=True),
    sa.Column('complaint_source', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_strength_grade', sa.String(length=100), nullable=True),
    sa.Column('batch_lot_number', sa.String(length=100), nullable=True),
    sa.Column('affected_quantity_text', sa.String(length=100), nullable=True),
    sa.Column('affected_quantity_value', sa.Numeric(), nullable=True),
    sa.Column('affected_quantity_unit', sa.String(length=50), nullable=True),
    sa.Column('manufacturing_date_text', sa.String(length=50), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_text', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('originating_site_block', sa.String(length=150), nullable=True),
    sa.Column('impacted_non_product_materials', sa.String(length=255), nullable=True),
    sa.Column('complaint_category', sa.String(length=255), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('suggested_severity', sa.String(length=20), nullable=True),
    sa.Column('suggested_next_action', sa.Text(), nullable=True),
    sa.Column('initial_risk_assessment', sa.Text(), nullable=True),
    sa.Column('raw_complaint_text', sa.Text(), nullable=True),
    sa.Column('input_type', sa.String(length=20), server_default=sa.text("'TEXT'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING_TRIAGE'"), nullable=False),
    sa.Column('is_committed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('committed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            input_type IN (\n                'TEXT',\n                'EMAIL',\n                'PDF',\n                'IMAGE',\n                'DOCUMENT'\n            )\n            ", name='chk_complaint_input_type'),
    sa.CheckConstraint("\n            status IN (\n                'PENDING_TRIAGE',\n                'PROCESSING',\n                'NEEDS_INFORMATION',\n                'READY_TO_COMMIT',\n                'COMMITTED',\n                'PROCESSING_FAILED'\n            )\n            ", name='chk_complaint_status'),
    sa.CheckConstraint("\n            suggested_severity IS NULL\n            OR suggested_severity IN ('MINOR', 'MAJOR', 'CRITICAL')\n            ", name='chk_complaint_severity'),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('complaint_number'),
    schema='public'
    )
    op.create_table('complaint_ai_runs',
    sa.Column('ai_run_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('model_provider', sa.String(length=50), server_default=sa.text("'GROQ'"), nullable=False),
    sa.Column('model_name', sa.String(length=100), server_default=sa.text("'llama-3.3-70b-versatile'"), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=255), nullable=True),
    sa.Column('langgraph_run_id', sa.String(length=255), nullable=True),
    sa.Column('run_status', sa.String(length=30), server_default=sa.text("'STARTED'"), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("\n            run_status IN (\n                'STARTED',\n                'PROCESSING',\n                'WAITING_FOR_USER',\n                'COMPLETED',\n                'FAILED'\n            )\n            ", name='chk_ai_run_status'),
    sa.CheckConstraint("\n            trigger_type IN (\n                'TEXT_SUBMISSION',\n                'FILE_UPLOAD',\n                'CHAT_CORRECTION',\n                'REANALYSIS'\n            )\n            ", name='chk_ai_trigger_type'),
    sa.ForeignKeyConstraint(['complaint_id'], ['public.complaints.complaint_id'], name='fk_ai_run_complaint'),
    sa.PrimaryKeyConstraint('ai_run_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_complaint_ai_runs_complaint_id'), 'complaint_ai_runs', ['complaint_id'], unique=False, schema='public')
    op.create_table('complaint_attachments',
    sa.Column('attachment_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.String(length=30), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            document_type IN (\n                'COMPLAINT_PDF',\n                'EMAIL',\n                'IMAGE',\n                'DOCX',\n                'TXT',\n                'OTHER'\n            )\n            ", name='chk_attachment_document_type'),
    sa.CheckConstraint("\n            extraction_status IN (\n                'PENDING',\n                'PROCESSING',\n                'COMPLETED',\n                'FAILED'\n            )\n            ", name='chk_attachment_extraction_status'),
    sa.ForeignKeyConstraint(['complaint_id'], ['public.complaints.complaint_id'], name='fk_attachment_complaint'),
    sa.PrimaryKeyConstraint('attachment_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_complaint_attachments_complaint_id'), 'complaint_attachments', ['complaint_id'], unique=False, schema='public')
    op.create_table('complaint_audit_logs',
    sa.Column('audit_log_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            performed_by IN (\n                'USER',\n                'AI',\n                'SYSTEM'\n            )\n            ", name='chk_audit_performed_by'),
    sa.ForeignKeyConstraint(['complaint_id'], ['public.complaints.complaint_id'], name='fk_audit_complaint'),
    sa.PrimaryKeyConstraint('audit_log_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_complaint_audit_logs_complaint_id'), 'complaint_audit_logs', ['complaint_id'], unique=False, schema='public')
    op.create_table('complaint_messages',
    sa.Column('message_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=30), server_default=sa.text("'TEXT'"), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            message_type IN (\n                'TEXT',\n                'FILE',\n                'EXTRACTION_RESULT',\n                'FIELD_UPDATE',\n                'ERROR'\n            )\n            ", name='chk_message_type'),
    sa.CheckConstraint("\n            sender_type IN (\n                'USER',\n                'ASSISTANT',\n                'SYSTEM'\n            )\n            ", name='chk_message_sender_type'),
    sa.ForeignKeyConstraint(['attachment_id'], ['public.complaint_attachments.attachment_id'], name='fk_message_attachment'),
    sa.ForeignKeyConstraint(['complaint_id'], ['public.complaints.complaint_id'], name='fk_message_complaint'),
    sa.PrimaryKeyConstraint('message_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_complaint_messages_attachment_id'), 'complaint_messages', ['attachment_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_complaint_messages_complaint_id'), 'complaint_messages', ['complaint_id'], unique=False, schema='public')
    op.create_table('complaint_field_changes',
    sa.Column('field_change_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('change_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            change_source IN (\n                'INITIAL_EXTRACTION',\n                'CHAT_CORRECTION',\n                'MANUAL_EDIT',\n                'FILE_REPROCESSING',\n                'SYSTEM_UPDATE'\n            )\n            ", name='chk_field_change_source'),
    sa.CheckConstraint("\n            changed_by IN (\n                'USER',\n                'AI',\n                'SYSTEM'\n            )\n            ", name='chk_field_changed_by'),
    sa.ForeignKeyConstraint(['ai_run_id'], ['public.complaint_ai_runs.ai_run_id'], name='fk_field_change_ai_run'),
    sa.ForeignKeyConstraint(['complaint_id'], ['public.complaints.complaint_id'], name='fk_field_change_complaint'),
    sa.ForeignKeyConstraint(['message_id'], ['public.complaint_messages.message_id'], name='fk_field_change_message'),
    sa.PrimaryKeyConstraint('field_change_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_complaint_field_changes_ai_run_id'), 'complaint_field_changes', ['ai_run_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_complaint_field_changes_complaint_id'), 'complaint_field_changes', ['complaint_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_complaint_field_changes_message_id'), 'complaint_field_changes', ['message_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_complaint_field_changes_message_id'), table_name='complaint_field_changes', schema='public')
    op.drop_index(op.f('ix_public_complaint_field_changes_complaint_id'), table_name='complaint_field_changes', schema='public')
    op.drop_index(op.f('ix_public_complaint_field_changes_ai_run_id'), table_name='complaint_field_changes', schema='public')
    op.drop_table('complaint_field_changes', schema='public')
    op.drop_index(op.f('ix_public_complaint_messages_complaint_id'), table_name='complaint_messages', schema='public')
    op.drop_index(op.f('ix_public_complaint_messages_attachment_id'), table_name='complaint_messages', schema='public')
    op.drop_table('complaint_messages', schema='public')
    op.drop_index(op.f('ix_public_complaint_audit_logs_complaint_id'), table_name='complaint_audit_logs', schema='public')
    op.drop_table('complaint_audit_logs', schema='public')
    op.drop_index(op.f('ix_public_complaint_attachments_complaint_id'), table_name='complaint_attachments', schema='public')
    op.drop_table('complaint_attachments', schema='public')
    op.drop_index(op.f('ix_public_complaint_ai_runs_complaint_id'), table_name='complaint_ai_runs', schema='public')
    op.drop_table('complaint_ai_runs', schema='public')
    op.drop_table('complaints', schema='public')
    # ### end Alembic commands ###
