from typing import List, Optional
from uuid import UUID

from sqlalchemy.orm import Session

from app.models.complaint_message import ComplaintMessage
from app.schemas.message import MessageCreate


class MessageRepository:
    """
    Handles database operations related to complaint messages.

    Messages may be created by the user, AI assistant, or system.
    This repository only handles database operations. Chat processing
    and AI logic will remain in the service and LangGraph layers.
    """

    def create_message(
        self,
        db: Session,
        message_data: MessageCreate,
    ) -> ComplaintMessage:
        """
        Create a new message for a complaint.
        """

        message = ComplaintMessage(
            **message_data.model_dump(exclude_unset=True)
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def get_message_by_id(
        self,
        db: Session,
        message_id: UUID,
    ) -> Optional[ComplaintMessage]:
        """
        Retrieve a message using its UUID.
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.message_id == message_id
            )
            .first()
        )

    def get_messages_by_complaint_id(
        self,
        db: Session,
        complaint_id: UUID,
    ) -> List[ComplaintMessage]:
        """
        Retrieve all messages belonging to a complaint.

        Messages are returned from oldest to newest so that they
        can be displayed as a normal conversation.
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.complaint_id == complaint_id
            )
            .order_by(
                ComplaintMessage.created_at.asc()
            )
            .all()
        )

    def get_latest_message(
        self,
        db: Session,
        complaint_id: UUID,
    ) -> Optional[ComplaintMessage]:
        """
        Retrieve the latest message for a complaint.
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.complaint_id == complaint_id
            )
            .order_by(
                ComplaintMessage.created_at.desc()
            )
            .first()
        )

    def get_messages_by_sender_type(
        self,
        db: Session,
        complaint_id: UUID,
        sender_type: str,
    ) -> List[ComplaintMessage]:
        """
        Retrieve complaint messages created by a specific sender.

        Supported sender types:
        USER
        ASSISTANT
        SYSTEM
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.complaint_id == complaint_id,
                ComplaintMessage.sender_type == sender_type,
            )
            .order_by(
                ComplaintMessage.created_at.asc()
            )
            .all()
        )

    def get_messages_by_message_type(
        self,
        db: Session,
        complaint_id: UUID,
        message_type: str,
    ) -> List[ComplaintMessage]:
        """
        Retrieve messages belonging to a specific message type.

        Supported message types:
        TEXT
        FILE
        EXTRACTION_RESULT
        FIELD_UPDATE
        ERROR
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.complaint_id == complaint_id,
                ComplaintMessage.message_type == message_type,
            )
            .order_by(
                ComplaintMessage.created_at.asc()
            )
            .all()
        )

    def create_user_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        attachment_id: Optional[UUID] = None,
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a message sent by the user.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            attachment_id=attachment_id,
            sender_type="USER",
            message_type="TEXT",
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_assistant_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        message_type: str = "TEXT",
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a response generated by the AI assistant.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            sender_type="ASSISTANT",
            message_type=message_type,
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_system_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        message_type: str = "TEXT",
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a system-generated complaint message.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            sender_type="SYSTEM",
            message_type=message_type,
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_file_message(
        self,
        db: Session,
        complaint_id: UUID,
        attachment_id: UUID,
        message_text: Optional[str] = None,
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a message representing an uploaded file.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            attachment_id=attachment_id,
            sender_type="USER",
            message_type="FILE",
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_extraction_result_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        attachment_id: Optional[UUID] = None,
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a message containing document or text extraction results.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            attachment_id=attachment_id,
            sender_type="ASSISTANT",
            message_type="EXTRACTION_RESULT",
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_field_update_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a message representing one or more field updates.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            sender_type="ASSISTANT",
            message_type="FIELD_UPDATE",
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def create_error_message(
        self,
        db: Session,
        complaint_id: UUID,
        message_text: str,
        message_metadata: Optional[dict] = None,
    ) -> ComplaintMessage:
        """
        Create a system error message for the complaint conversation.
        """

        message = ComplaintMessage(
            complaint_id=complaint_id,
            sender_type="SYSTEM",
            message_type="ERROR",
            message_text=message_text,
            message_metadata=message_metadata or {},
        )

        db.add(message)
        db.flush()
        db.refresh(message)

        return message

    def count_messages_by_complaint_id(
        self,
        db: Session,
        complaint_id: UUID,
    ) -> int:
        """
        Count all messages belonging to a complaint.
        """

        return (
            db.query(ComplaintMessage)
            .filter(
                ComplaintMessage.complaint_id == complaint_id
            )
            .count()
        )

    def message_belongs_to_complaint(
        self,
        db: Session,
        message_id: UUID,
        complaint_id: UUID,
    ) -> bool:
        """
        Check whether a message belongs to a specific complaint.
        """

        message = (
            db.query(ComplaintMessage.message_id)
            .filter(
                ComplaintMessage.message_id == message_id,
                ComplaintMessage.complaint_id == complaint_id,
            )
            .first()
        )

        return message is not None

    def delete_message(
        self,
        db: Session,
        message: ComplaintMessage,
    ) -> None:
        """
        Delete a message record.

        The service layer should allow this only while the complaint
        is still an uncommitted draft.
        """

        db.delete(message)
        db.flush()